# Generated by Django 5.1.3 on 2024-11-24 12:45

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('is_calculated', models.BooleanField(default=False)),
                ('is_calculated2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_teacher', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee_student', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_fee_teacher', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_admin_only', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount of money paid.', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the payment was made.')),
                ('invoice_type', models.CharField(choices=[('inscription', 'Inscription'), ('atelier', 'Atelier'), ('solde', 'Solde Client')], default='inscription', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('matricule', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('parent_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('student', 'Etudiant'), ('teacher', 'Enseignant'), ('none', 'Non Etudiant')], default='student', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('absence_alert', models.DateField(blank=True, help_text='Date of the absence alert.', null=True)),
                ('upcoming_absence_date', models.DateField(blank=True, help_text='Date of the next planned absence.', null=True)),
                ('rattrappage', models.DateTimeField(blank=True, help_text='Date and time for any makeup class or session.', null=True)),
                ('registration_type', models.CharField(choices=[('none', "Pas d'inscription"), ('bimestriel', 'Bimestriel'), ('annual', 'Annuel')], default='none', max_length=20)),
                ('facture', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Amount of the facture issued.', max_digits=10, null=True)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments.', null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profit_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message="Le nom d'utilisateur ne peut contenir que des lettres, des chiffres, des espaces et les symboles @/./+/-/_", regex='^[\\w.@+\\-\\s]+$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
