# Generated by Django 5.1.3 on 2024-11-24 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_ressorces', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='pages.painting'),
        ),
        migrations.AddField(
            model_name='absence',
            name='atelier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_ressorces.atelier'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='atelier_absent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absent_profiles', to='human_ressorces.atelier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ateliers',
            field=models.ManyToManyField(blank=True, to='human_ressorces.atelier'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='human_ressorces.group'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='human_ressorces.profile'),
        ),
        migrations.AddField(
            model_name='absence',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_ressorces.profile'),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('profile', 'date_from', 'atelier')},
        ),
    ]
