# Generated by Django 5.1.3 on 2024-11-30 11:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier_Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_ressorces.atelier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_ressorces.profile')),
            ],
            options={
                'unique_together': {('profile', 'atelier')},
            },
        ),
    ]
