# Generated by Django 5.1.3 on 2024-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0003_atelier_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier_facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
