# Generated by Django 5.1.3 on 2024-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0004_atelier_facture_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atelier_facture',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='atelier_facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atelier_facture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
