# Generated by Django 5.1.3 on 2024-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0005_alter_atelier_facture_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier_facture',
            name='facture_type',
            field=models.CharField(choices=[('inscription', 'Inscription'), ('atelier', 'Atelier')], default='atelier', max_length=20),
        ),
    ]
