# Generated by Django 5.1.3 on 2024-11-30 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0006_atelier_facture_facture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier_facture',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_ressorces.atelier'),
        ),
    ]
