# Generated by Django 5.1.3 on 2024-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0007_alter_atelier_facture_atelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='invoice_type',
            field=models.CharField(choices=[('facture', 'Facture'), ('solde', 'Solde Client')], default='facture', max_length=20),
        ),
    ]
