# Generated by Django 5.1.4 on 2024-12-06 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0009_customuser_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='financialstats',
            name='unique_visitors',
            field=models.ManyToManyField(blank=True, to='human_ressorces.visitorip'),
        ),
    ]
