# Generated by Django 5.1.4 on 2024-12-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_ressorces', '0010_visitorip_financialstats_unique_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorip',
            name='is_me',
            field=models.BooleanField(default=False),
        ),
    ]
